services:
  backend:
    build:
      context: ./backend
    container_name: cv-backend
    ports:
      - "4005:4005"
    env_file:
      - ./backend/.env

  front:
    build:
      context: ./front
    container_name: cv-front
    ports:
      - "3011:3011"
    env_file:
      - ./front/.env
    depends_on:
      - backend